version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  api:
    build: ./api
    container_name: api_app
    ports:
      - "8000:8000"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DB=${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./api:/app
  
  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
  

volumes:
  pgdata: